### ISSUE TITLE
Is the Example.coffeescript file missing?

### ISSUE THREAD

**Issue by jamatsui** [robotdestroy/Framer-Snippets-Library#5]
It's awesome that you published this. I'm a beginner playing around with Framer a bit more. Was unable to find the Example.coffeescript file. Wondering if I'm missing something.

Thanks in advance!

-Jason

**Comment by robotdestroy** [comment]
There's no examples to the Snippet library. After you import you can access the snippets from the snippets menu.

I made these two videos to show how they work:

https://www.youtube.com/watch?v=CgY6fT7HwAw <https://www.youtube.com/watch?v=CgY6fT7HwAw>
https://www.youtube.com/watch?v=p_J0jd-JYZU <https://www.youtube.com/watch?v=p_J0jd-JYZU>

Hope that helps,
Charlie

**Comment by jamatsui** [comment]
Thanks Charlie, those were super helpful. It gave me a few ideas on how to use the framework and general workflow ideas. Feels like there's some advantage to building some layers directly into Framer vs in Sketch. Submitted a small PR to address the question I had here and added those videos. Hope that's useful.

Thanks again,
Jason

**Comment by robotdestroy** [comment]
Thanks @jamatsui!
